#!/usr/bin/env bash
# install-witness.sh — provisions one DAQ witness on a fresh host
# (Ubuntu 22.04+ / Debian 12+). Idempotent: re-running is safe.
#
# Invariants the install enforces:
#
#   * `963causal` system user + group, shell=nologin, home=/var/lib/963causal.
#   * Binary at /usr/local/bin/963causal-witness (0755, root-owned).
#   * BLS private key at /var/lib/963causal/daq/witness-NN.key (0600, 963causal).
#   * Auth token at /var/lib/963causal/daq/witness-NN.key.token (0400, 963causal).
#   * systemd unit 963causal-witness@NN.service + EnvironmentFile.
#   * Firewall: port opened to a supplied allowlist (control-plane IP +
#     any other witness peers you trust). If UFW is not active we log
#     a warning and proceed — operator is responsible for the filter.
#
# Usage (on the target VM, as root):
#
#   scp bin/963causal-witness ubuntu@tokyo:/tmp/
#   scp witness-00.key witness-00.key.token ubuntu@tokyo:/tmp/
#   scp deploy/systemd/963causal-witness@.service ubuntu@tokyo:/tmp/
#   ssh tokyo 'sudo bash -s' < deploy/scripts/install-witness.sh \
#     --index 0 --label tokyo \
#     --addr 0.0.0.0:17001 \
#     --key /tmp/witness-00.key --token /tmp/witness-00.key.token \
#     --binary /tmp/963causal-witness \
#     --unit-template /tmp/963causal-witness@.service \
#     --allow-from 203.0.113.10
#
# The control-plane operator then runs (on their laptop or the
# control-plane host):
#
#   npm run daq:seed-roster -- roster.json --force-rotate --label=v2-global
#
# which flips the active roster atomically.

set -euo pipefail

INDEX=
LABEL=
ADDR=
KEY_SRC=
TOKEN_SRC=
BIN_SRC=
UNIT_SRC=
ALLOW_FROM=
DRAND_CHAIN="52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971"
CHAIN_PUBKEY="83cf0f2896adee7eb8b5f01fcad3912212c437e0073e911fb90022d3e760183c8c4b450b6a0a6c3ac6a5776a2d1064510d1fec758c921cc22b0e17e63aaf4bcb5ed66304de9cf809bd274ca73bab4af5a6e9c76a4bc09e76eae8991ef5ece45a"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --index)          INDEX="$2"; shift 2 ;;
    --label)          LABEL="$2"; shift 2 ;;
    --addr)           ADDR="$2"; shift 2 ;;
    --key)            KEY_SRC="$2"; shift 2 ;;
    --token)          TOKEN_SRC="$2"; shift 2 ;;
    --binary)         BIN_SRC="$2"; shift 2 ;;
    --unit-template)  UNIT_SRC="$2"; shift 2 ;;
    --allow-from)     ALLOW_FROM="$2"; shift 2 ;;
    --drand-chain)    DRAND_CHAIN="$2"; shift 2 ;;
    --chain-pubkey)   CHAIN_PUBKEY="$2"; shift 2 ;;
    -h|--help)
      sed -n '1,45p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *)
      echo "unknown flag: $1" >&2
      exit 2 ;;
  esac
done

require() {
  local name="$1"; local val="$2"
  if [[ -z "$val" ]]; then echo "missing required flag: --${name//_/-}" >&2; exit 2; fi
}
require index     "$INDEX"
require label     "$LABEL"
require addr      "$ADDR"
require key       "$KEY_SRC"
require token     "$TOKEN_SRC"
require binary    "$BIN_SRC"
require unit-template "$UNIT_SRC"

if [[ "$EUID" -ne 0 ]]; then
  echo "must run as root (use sudo)" >&2
  exit 2
fi

IDX_PADDED=$(printf "%02d" "$INDEX")

echo "[1/7] Ensure 963causal user + home"
if ! id 963causal >/dev/null 2>&1; then
  useradd --system --home-dir /var/lib/963causal --create-home --shell /usr/sbin/nologin 963causal
fi
install -d -o 963causal -g 963causal -m 0750 /var/lib/963causal /var/lib/963causal/daq /var/log/963causal
install -d -o root -g root -m 0755 /etc/963causal

echo "[2/7] Install binary → /usr/local/bin/963causal-witness"
install -o root -g root -m 0755 "$BIN_SRC" /usr/local/bin/963causal-witness

echo "[3/7] Install BLS key + auth token → /var/lib/963causal/daq/"
KEY_DST="/var/lib/963causal/daq/witness-${IDX_PADDED}.key"
TOK_DST="${KEY_DST}.token"
install -o 963causal -g 963causal -m 0600 "$KEY_SRC"   "$KEY_DST"
install -o 963causal -g 963causal -m 0400 "$TOKEN_SRC" "$TOK_DST"

echo "[4/7] Install systemd unit template"
install -o root -g root -m 0644 "$UNIT_SRC" /etc/systemd/system/963causal-witness@.service

echo "[5/7] Write EnvironmentFile for witness ${IDX_PADDED}"
cat > /etc/963causal/witness-${INDEX}.env <<ENV
# Generated by install-witness.sh on $(date --iso-8601=seconds)
# Do not edit unless rotating: the corresponding DB row must match.
WITNESS_INDEX=${INDEX}
WITNESS_LABEL=${LABEL}
WITNESS_ADDR=${ADDR}
WITNESS_KEY_FILE=${KEY_DST}
WITNESS_TOKEN_FILE=${TOK_DST}
WITNESS_DRAND_CHAIN=${DRAND_CHAIN}
WITNESS_CHAIN_PUBKEY=${CHAIN_PUBKEY}
ENV
chmod 0640 /etc/963causal/witness-${INDEX}.env
chown root:963causal /etc/963causal/witness-${INDEX}.env

echo "[6/7] Enable + start systemd unit"
systemctl daemon-reload
systemctl enable --now "963causal-witness@${INDEX}.service"

echo "[7/7] Firewall (best-effort)"
PORT="${ADDR##*:}"
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  if [[ -n "$ALLOW_FROM" ]]; then
    ufw allow from "$ALLOW_FROM" to any port "$PORT" proto tcp comment "963causal-witness-${INDEX}"
    echo "  ufw: opened ${PORT}/tcp from ${ALLOW_FROM}"
  else
    echo "  ufw: no --allow-from supplied; leaving port ${PORT} unexposed (default deny)"
  fi
else
  echo "  ufw inactive; configure your cloud security group to permit ${PORT}/tcp from the control plane only"
fi

echo
echo "=== done — witness ${IDX_PADDED} is up on ${ADDR} ==="
systemctl --no-pager status "963causal-witness@${INDEX}.service" | head -12 || true
echo
echo "Next step on the control plane:"
echo "  npm run daq:seed-roster -- <new-roster.json> --label=v2-global --force-rotate"
