// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey    string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`          // provisioned at install time
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`             // Ed25519 public key (32 bytes)
	X25519Public  []byte                 `protobuf:"bytes,3,opt,name=x25519_public,json=x25519Public,proto3" json:"x25519_public,omitempty"`    // X25519 public key (32 bytes) for ECDH
	HwFingerprint string                 `protobuf:"bytes,4,opt,name=hw_fingerprint,json=hwFingerprint,proto3" json:"hw_fingerprint,omitempty"` // sha3-256 hex of hardware identifiers
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsRelease     string                 `protobuf:"bytes,7,opt,name=os_release,json=osRelease,proto3" json:"os_release,omitempty"`
	Kernel        string                 `protobuf:"bytes,8,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CpuModel      string                 `protobuf:"bytes,9,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	TotalMemoryKb uint64                 `protobuf:"varint,10,opt,name=total_memory_kb,json=totalMemoryKb,proto3" json:"total_memory_kb,omitempty"`
	Nonce         int64                  `protobuf:"varint,11,opt,name=nonce,proto3" json:"nonce,omitempty"` // anti-replay
	TimestampUnix int64                  `protobuf:"varint,12,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *EnrollRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EnrollRequest) GetX25519Public() []byte {
	if x != nil {
		return x.X25519Public
	}
	return nil
}

func (x *EnrollRequest) GetHwFingerprint() string {
	if x != nil {
		return x.HwFingerprint
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOsRelease() string {
	if x != nil {
		return x.OsRelease
	}
	return ""
}

func (x *EnrollRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *EnrollRequest) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *EnrollRequest) GetTotalMemoryKb() uint64 {
	if x != nil {
		return x.TotalMemoryKb
	}
	return 0
}

func (x *EnrollRequest) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *EnrollRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type EnrollResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HostId               string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentToken           string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`                   // opaque bearer for frame/heartbeat
	ServerX25519Pub      []byte                 `protobuf:"bytes,3,opt,name=server_x25519_pub,json=serverX25519Pub,proto3" json:"server_x25519_pub,omitempty"`  // ECDH server pub (32 bytes)
	EncryptedPayload     []byte                 `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // ChaCha20-Poly1305 ciphertext of probe config
	PayloadNonce         []byte                 `protobuf:"bytes,5,opt,name=payload_nonce,json=payloadNonce,proto3" json:"payload_nonce,omitempty"`             // 12 bytes
	HeartbeatIntervalSec uint32                 `protobuf:"varint,6,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	FrameEpochSec        uint32                 `protobuf:"varint,7,opt,name=frame_epoch_sec,json=frameEpochSec,proto3" json:"frame_epoch_sec,omitempty"`    // seconds per measurement epoch
	GracePeriodSec       uint32                 `protobuf:"varint,8,opt,name=grace_period_sec,json=gracePeriodSec,proto3" json:"grace_period_sec,omitempty"` // how long agent may run without heartbeat
	// Same derivation as DB agent_enrollments.causalId (SHA-256(pub) hex prefix).
	CausalId      string `protobuf:"bytes,9,opt,name=causal_id,json=causalId,proto3" json:"causal_id,omitempty"` // e.g. CID-963-XXXXXXXX-XXXXXXXX for public verify portal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *EnrollResponse) GetServerX25519Pub() []byte {
	if x != nil {
		return x.ServerX25519Pub
	}
	return nil
}

func (x *EnrollResponse) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *EnrollResponse) GetPayloadNonce() []byte {
	if x != nil {
		return x.PayloadNonce
	}
	return nil
}

func (x *EnrollResponse) GetHeartbeatIntervalSec() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *EnrollResponse) GetFrameEpochSec() uint32 {
	if x != nil {
		return x.FrameEpochSec
	}
	return 0
}

func (x *EnrollResponse) GetGracePeriodSec() uint32 {
	if x != nil {
		return x.GracePeriodSec
	}
	return 0
}

func (x *EnrollResponse) GetCausalId() string {
	if x != nil {
		return x.CausalId
	}
	return ""
}

type ProbeConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	EpochSec                   uint32                 `protobuf:"varint,1,opt,name=epoch_sec,json=epochSec,proto3" json:"epoch_sec,omitempty"`
	SyscallProbes              []string               `protobuf:"bytes,2,rep,name=syscall_probes,json=syscallProbes,proto3" json:"syscall_probes,omitempty"` // e.g. ["read","write","openat","execve","connect","accept"]
	SampleSchedstat            bool                   `protobuf:"varint,3,opt,name=sample_schedstat,json=sampleSchedstat,proto3" json:"sample_schedstat,omitempty"`
	SamplePageFaults           bool                   `protobuf:"varint,4,opt,name=sample_page_faults,json=samplePageFaults,proto3" json:"sample_page_faults,omitempty"`
	SampleTcpRtt               bool                   `protobuf:"varint,5,opt,name=sample_tcp_rtt,json=sampleTcpRtt,proto3" json:"sample_tcp_rtt,omitempty"`
	HistogramSignificantDigits uint32                 `protobuf:"varint,6,opt,name=histogram_significant_digits,json=histogramSignificantDigits,proto3" json:"histogram_significant_digits,omitempty"` // HDR precision (2 or 3)
	Version                    uint64                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`                                                                           // probe config version counter
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ProbeConfig) Reset() {
	*x = ProbeConfig{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConfig) ProtoMessage() {}

func (x *ProbeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConfig.ProtoReflect.Descriptor instead.
func (*ProbeConfig) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeConfig) GetEpochSec() uint32 {
	if x != nil {
		return x.EpochSec
	}
	return 0
}

func (x *ProbeConfig) GetSyscallProbes() []string {
	if x != nil {
		return x.SyscallProbes
	}
	return nil
}

func (x *ProbeConfig) GetSampleSchedstat() bool {
	if x != nil {
		return x.SampleSchedstat
	}
	return false
}

func (x *ProbeConfig) GetSamplePageFaults() bool {
	if x != nil {
		return x.SamplePageFaults
	}
	return false
}

func (x *ProbeConfig) GetSampleTcpRtt() bool {
	if x != nil {
		return x.SampleTcpRtt
	}
	return false
}

func (x *ProbeConfig) GetHistogramSignificantDigits() uint32 {
	if x != nil {
		return x.HistogramSignificantDigits
	}
	return 0
}

func (x *ProbeConfig) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Frame struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	HostId     string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Sequence   uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                       // monotonic per-agent
	EpochStart int64                  `protobuf:"varint,3,opt,name=epoch_start,json=epochStart,proto3" json:"epoch_start,omitempty"` // unix millis
	EpochEnd   int64                  `protobuf:"varint,4,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`       // unix millis
	// Syscall latency histograms (one per probed syscall).
	SyscallHist []*HdrHistogram `protobuf:"bytes,5,rep,name=syscall_hist,json=syscallHist,proto3" json:"syscall_hist,omitempty"`
	// Scheduler fingerprint
	Sched *SchedulerDigest `protobuf:"bytes,6,opt,name=sched,proto3" json:"sched,omitempty"`
	// Page fault counters
	Faults *FaultDigest `protobuf:"bytes,7,opt,name=faults,proto3" json:"faults,omitempty"`
	// Derived vertices for sculpture reconstruction (24-dim default).
	Vertices []float64 `protobuf:"fixed64,8,rep,packed,name=vertices,proto3" json:"vertices,omitempty"`
	// Preliminary genotype computed on the agent (server recomputes).
	Genotype string `protobuf:"bytes,9,opt,name=genotype,proto3" json:"genotype,omitempty"`
	// Hardware + environment re-check
	HwFingerprint string `protobuf:"bytes,10,opt,name=hw_fingerprint,json=hwFingerprint,proto3" json:"hw_fingerprint,omitempty"`
	// W3: Multi-Source Time Consensus (physics layer).
	// Measures divergence between independent time sources. On bare metal the
	// hardware counter ratio is exactly 1.0; under a manipulative hypervisor or
	// rootkit intercepting the time path, it drifts.
	TimeConsensus *TimeConsensusDigest `protobuf:"bytes,11,opt,name=time_consensus,json=timeConsensus,proto3" json:"time_consensus,omitempty"`
	// W3: External Witness — an unforgeable external reference (drand beacon)
	// proving the agent was executing inside a specific real-time window that
	// no offline adversary could have predicted in advance.
	Witness *ExternalWitness `protobuf:"bytes,12,opt,name=witness,proto3" json:"witness,omitempty"`
	// Anti-replay anchor (H-05): signed generation timestamp.
	// Server MUST reject frames where |server_time - GeneratedAtMs| > 2*epoch_sec*1000.
	GeneratedAtMs int64 `protobuf:"varint,13,opt,name=generated_at_ms,json=generatedAtMs,proto3" json:"generated_at_ms,omitempty"`
	// Anti-replay nonce (H-05): 16 random bytes mixed into the signed payload.
	// Server MUST track (host_id, frame_nonce) and reject duplicates.
	FrameNonce    []byte `protobuf:"bytes,14,opt,name=frame_nonce,json=frameNonce,proto3" json:"frame_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Frame) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Frame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Frame) GetEpochStart() int64 {
	if x != nil {
		return x.EpochStart
	}
	return 0
}

func (x *Frame) GetEpochEnd() int64 {
	if x != nil {
		return x.EpochEnd
	}
	return 0
}

func (x *Frame) GetSyscallHist() []*HdrHistogram {
	if x != nil {
		return x.SyscallHist
	}
	return nil
}

func (x *Frame) GetSched() *SchedulerDigest {
	if x != nil {
		return x.Sched
	}
	return nil
}

func (x *Frame) GetFaults() *FaultDigest {
	if x != nil {
		return x.Faults
	}
	return nil
}

func (x *Frame) GetVertices() []float64 {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *Frame) GetGenotype() string {
	if x != nil {
		return x.Genotype
	}
	return ""
}

func (x *Frame) GetHwFingerprint() string {
	if x != nil {
		return x.HwFingerprint
	}
	return ""
}

func (x *Frame) GetTimeConsensus() *TimeConsensusDigest {
	if x != nil {
		return x.TimeConsensus
	}
	return nil
}

func (x *Frame) GetWitness() *ExternalWitness {
	if x != nil {
		return x.Witness
	}
	return nil
}

func (x *Frame) GetGeneratedAtMs() int64 {
	if x != nil {
		return x.GeneratedAtMs
	}
	return 0
}

func (x *Frame) GetFrameNonce() []byte {
	if x != nil {
		return x.FrameNonce
	}
	return nil
}

// TimeConsensusDigest captures statistics comparing multiple independent
// clock sources over the epoch. See internal/probe/mstc.go for the math.
//
//	HW      = ARM CNTVCT_EL0 / x86 RDTSC  (hardware-architected counter)
//	HW2     = ARM CNTPCT_EL0 / x86 RDTSCP (alternate hardware path)
//	VDSO    = clock_gettime(CLOCK_MONOTONIC_RAW) via vDSO fast path
//	SYSCALL = same clock via forced syscall (SYS_clock_gettime)
//
// Null hypothesis on clean bare metal: all four advance at the same rate,
// modulo tiny phase noise (~1e-6 relative). Hypervisors/rootkits that
// intercept any single path introduce measurable divergence.
type TimeConsensusDigest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Architecture of the measurement host (arm64 | amd64).
	Arch string `protobuf:"bytes,1,opt,name=arch,proto3" json:"arch,omitempty"`
	// Hardware counter frequency in Hz (CNTFRQ_EL0 on ARM, estimated on x86).
	HwHz uint64 `protobuf:"varint,2,opt,name=hw_hz,json=hwHz,proto3" json:"hw_hz,omitempty"`
	// Ratio statistics over the epoch, computed with Welford's online algorithm.
	// ratio_hw_vdso = Δ(HW)/Δ(VDSO)   — baseline 1.0 on bare metal.
	RatioHwVdsoMean   float64 `protobuf:"fixed64,3,opt,name=ratio_hw_vdso_mean,json=ratioHwVdsoMean,proto3" json:"ratio_hw_vdso_mean,omitempty"`
	RatioHwVdsoStddev float64 `protobuf:"fixed64,4,opt,name=ratio_hw_vdso_stddev,json=ratioHwVdsoStddev,proto3" json:"ratio_hw_vdso_stddev,omitempty"`
	// ratio_vdso_syscall = Δ(VDSO)/Δ(SYSCALL) — baseline 1.0; diverges when
	// vdso is bypassed or when syscall path is trapped by a hypervisor.
	RatioVdsoSyscallMean   float64 `protobuf:"fixed64,5,opt,name=ratio_vdso_syscall_mean,json=ratioVdsoSyscallMean,proto3" json:"ratio_vdso_syscall_mean,omitempty"`
	RatioVdsoSyscallStddev float64 `protobuf:"fixed64,6,opt,name=ratio_vdso_syscall_stddev,json=ratioVdsoSyscallStddev,proto3" json:"ratio_vdso_syscall_stddev,omitempty"`
	// ratio_hw_hw2 = Δ(HW)/Δ(HW2) — baseline 1.0; diverges only if two distinct
	// counter-read paths are intercepted inconsistently.
	RatioHwHw2Mean   float64 `protobuf:"fixed64,7,opt,name=ratio_hw_hw2_mean,json=ratioHwHw2Mean,proto3" json:"ratio_hw_hw2_mean,omitempty"`
	RatioHwHw2Stddev float64 `protobuf:"fixed64,8,opt,name=ratio_hw_hw2_stddev,json=ratioHwHw2Stddev,proto3" json:"ratio_hw_hw2_stddev,omitempty"`
	// Per-sample latency histograms (cycles) for each time source. A hidden
	// hypervisor inflates the tail of instructions that it traps (e.g. RDTSC
	// with TSC_OFFSETTING disabled; CNTVCT_EL0 under EL2 trap).
	// Values are p50 and p99 in nanoseconds (derived from cycle counts / hw_hz).
	HwReadP50Ns      float64 `protobuf:"fixed64,9,opt,name=hw_read_p50_ns,json=hwReadP50Ns,proto3" json:"hw_read_p50_ns,omitempty"`
	HwReadP99Ns      float64 `protobuf:"fixed64,10,opt,name=hw_read_p99_ns,json=hwReadP99Ns,proto3" json:"hw_read_p99_ns,omitempty"`
	VdsoReadP50Ns    float64 `protobuf:"fixed64,11,opt,name=vdso_read_p50_ns,json=vdsoReadP50Ns,proto3" json:"vdso_read_p50_ns,omitempty"`
	VdsoReadP99Ns    float64 `protobuf:"fixed64,12,opt,name=vdso_read_p99_ns,json=vdsoReadP99Ns,proto3" json:"vdso_read_p99_ns,omitempty"`
	SyscallReadP50Ns float64 `protobuf:"fixed64,13,opt,name=syscall_read_p50_ns,json=syscallReadP50Ns,proto3" json:"syscall_read_p50_ns,omitempty"`
	SyscallReadP99Ns float64 `protobuf:"fixed64,14,opt,name=syscall_read_p99_ns,json=syscallReadP99Ns,proto3" json:"syscall_read_p99_ns,omitempty"`
	SampleCount      uint32  `protobuf:"varint,15,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeConsensusDigest) Reset() {
	*x = TimeConsensusDigest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeConsensusDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeConsensusDigest) ProtoMessage() {}

func (x *TimeConsensusDigest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeConsensusDigest.ProtoReflect.Descriptor instead.
func (*TimeConsensusDigest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TimeConsensusDigest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *TimeConsensusDigest) GetHwHz() uint64 {
	if x != nil {
		return x.HwHz
	}
	return 0
}

func (x *TimeConsensusDigest) GetRatioHwVdsoMean() float64 {
	if x != nil {
		return x.RatioHwVdsoMean
	}
	return 0
}

func (x *TimeConsensusDigest) GetRatioHwVdsoStddev() float64 {
	if x != nil {
		return x.RatioHwVdsoStddev
	}
	return 0
}

func (x *TimeConsensusDigest) GetRatioVdsoSyscallMean() float64 {
	if x != nil {
		return x.RatioVdsoSyscallMean
	}
	return 0
}

func (x *TimeConsensusDigest) GetRatioVdsoSyscallStddev() float64 {
	if x != nil {
		return x.RatioVdsoSyscallStddev
	}
	return 0
}

func (x *TimeConsensusDigest) GetRatioHwHw2Mean() float64 {
	if x != nil {
		return x.RatioHwHw2Mean
	}
	return 0
}

func (x *TimeConsensusDigest) GetRatioHwHw2Stddev() float64 {
	if x != nil {
		return x.RatioHwHw2Stddev
	}
	return 0
}

func (x *TimeConsensusDigest) GetHwReadP50Ns() float64 {
	if x != nil {
		return x.HwReadP50Ns
	}
	return 0
}

func (x *TimeConsensusDigest) GetHwReadP99Ns() float64 {
	if x != nil {
		return x.HwReadP99Ns
	}
	return 0
}

func (x *TimeConsensusDigest) GetVdsoReadP50Ns() float64 {
	if x != nil {
		return x.VdsoReadP50Ns
	}
	return 0
}

func (x *TimeConsensusDigest) GetVdsoReadP99Ns() float64 {
	if x != nil {
		return x.VdsoReadP99Ns
	}
	return 0
}

func (x *TimeConsensusDigest) GetSyscallReadP50Ns() float64 {
	if x != nil {
		return x.SyscallReadP50Ns
	}
	return 0
}

func (x *TimeConsensusDigest) GetSyscallReadP99Ns() float64 {
	if x != nil {
		return x.SyscallReadP99Ns
	}
	return 0
}

func (x *TimeConsensusDigest) GetSampleCount() uint32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

// ExternalWitness carries a freshly-fetched public randomness beacon value
// that the agent captured during this epoch. The server verifies the round
// number and signature against the public drand chain, proving the frame
// could not have been pre-fabricated offline.
//
// Chain used: League of Entropy (https://drand.love) — 30-second rounds,
// BLS12-381 threshold signature from 15+ independent operators.
type ExternalWitness struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// drand chain hash (identifies the public BLS key set).
	ChainHash string `protobuf:"bytes,1,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// Round number at the time of capture.
	Round uint64 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	// 32-byte beacon randomness value.
	Randomness []byte `protobuf:"bytes,3,opt,name=randomness,proto3" json:"randomness,omitempty"`
	// BLS threshold signature for this round (verifiable against chain pubkey).
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Unix time in milliseconds when the agent completed the fetch.
	CapturedAtMs int64 `protobuf:"varint,5,opt,name=captured_at_ms,json=capturedAtMs,proto3" json:"captured_at_ms,omitempty"`
	// Round time published by drand (unix seconds). Server asserts
	// |captured_at_ms/1000 - round_time_unix| < bound.
	RoundTimeUnix int64 `protobuf:"varint,6,opt,name=round_time_unix,json=roundTimeUnix,proto3" json:"round_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalWitness) Reset() {
	*x = ExternalWitness{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalWitness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalWitness) ProtoMessage() {}

func (x *ExternalWitness) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalWitness.ProtoReflect.Descriptor instead.
func (*ExternalWitness) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExternalWitness) GetChainHash() string {
	if x != nil {
		return x.ChainHash
	}
	return ""
}

func (x *ExternalWitness) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ExternalWitness) GetRandomness() []byte {
	if x != nil {
		return x.Randomness
	}
	return nil
}

func (x *ExternalWitness) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ExternalWitness) GetCapturedAtMs() int64 {
	if x != nil {
		return x.CapturedAtMs
	}
	return 0
}

func (x *ExternalWitness) GetRoundTimeUnix() int64 {
	if x != nil {
		return x.RoundTimeUnix
	}
	return 0
}

type HdrHistogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Syscall       string                 `protobuf:"bytes,1,opt,name=syscall,proto3" json:"syscall,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	P50Ns         float64                `protobuf:"fixed64,3,opt,name=p50_ns,json=p50Ns,proto3" json:"p50_ns,omitempty"`
	P90Ns         float64                `protobuf:"fixed64,4,opt,name=p90_ns,json=p90Ns,proto3" json:"p90_ns,omitempty"`
	P99Ns         float64                `protobuf:"fixed64,5,opt,name=p99_ns,json=p99Ns,proto3" json:"p99_ns,omitempty"`
	P999Ns        float64                `protobuf:"fixed64,6,opt,name=p999_ns,json=p999Ns,proto3" json:"p999_ns,omitempty"`
	StddevNs      float64                `protobuf:"fixed64,7,opt,name=stddev_ns,json=stddevNs,proto3" json:"stddev_ns,omitempty"`
	MeanNs        float64                `protobuf:"fixed64,8,opt,name=mean_ns,json=meanNs,proto3" json:"mean_ns,omitempty"`
	CompactBlob   []byte                 `protobuf:"bytes,9,opt,name=compact_blob,json=compactBlob,proto3" json:"compact_blob,omitempty"` // optional compressed full histogram
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HdrHistogram) Reset() {
	*x = HdrHistogram{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HdrHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HdrHistogram) ProtoMessage() {}

func (x *HdrHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HdrHistogram.ProtoReflect.Descriptor instead.
func (*HdrHistogram) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HdrHistogram) GetSyscall() string {
	if x != nil {
		return x.Syscall
	}
	return ""
}

func (x *HdrHistogram) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *HdrHistogram) GetP50Ns() float64 {
	if x != nil {
		return x.P50Ns
	}
	return 0
}

func (x *HdrHistogram) GetP90Ns() float64 {
	if x != nil {
		return x.P90Ns
	}
	return 0
}

func (x *HdrHistogram) GetP99Ns() float64 {
	if x != nil {
		return x.P99Ns
	}
	return 0
}

func (x *HdrHistogram) GetP999Ns() float64 {
	if x != nil {
		return x.P999Ns
	}
	return 0
}

func (x *HdrHistogram) GetStddevNs() float64 {
	if x != nil {
		return x.StddevNs
	}
	return 0
}

func (x *HdrHistogram) GetMeanNs() float64 {
	if x != nil {
		return x.MeanNs
	}
	return 0
}

func (x *HdrHistogram) GetCompactBlob() []byte {
	if x != nil {
		return x.CompactBlob
	}
	return nil
}

type SchedulerDigest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunqueueDelayP50Ns  float64                `protobuf:"fixed64,1,opt,name=runqueue_delay_p50_ns,json=runqueueDelayP50Ns,proto3" json:"runqueue_delay_p50_ns,omitempty"`
	RunqueueDelayP99Ns  float64                `protobuf:"fixed64,2,opt,name=runqueue_delay_p99_ns,json=runqueueDelayP99Ns,proto3" json:"runqueue_delay_p99_ns,omitempty"`
	ContextSwitches     uint64                 `protobuf:"varint,3,opt,name=context_switches,json=contextSwitches,proto3" json:"context_switches,omitempty"`
	VoluntarySwitches   uint64                 `protobuf:"varint,4,opt,name=voluntary_switches,json=voluntarySwitches,proto3" json:"voluntary_switches,omitempty"`
	InvoluntarySwitches uint64                 `protobuf:"varint,5,opt,name=involuntary_switches,json=involuntarySwitches,proto3" json:"involuntary_switches,omitempty"`
	Load_1M             float64                `protobuf:"fixed64,6,opt,name=load_1m,json=load1m,proto3" json:"load_1m,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SchedulerDigest) Reset() {
	*x = SchedulerDigest{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerDigest) ProtoMessage() {}

func (x *SchedulerDigest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerDigest.ProtoReflect.Descriptor instead.
func (*SchedulerDigest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SchedulerDigest) GetRunqueueDelayP50Ns() float64 {
	if x != nil {
		return x.RunqueueDelayP50Ns
	}
	return 0
}

func (x *SchedulerDigest) GetRunqueueDelayP99Ns() float64 {
	if x != nil {
		return x.RunqueueDelayP99Ns
	}
	return 0
}

func (x *SchedulerDigest) GetContextSwitches() uint64 {
	if x != nil {
		return x.ContextSwitches
	}
	return 0
}

func (x *SchedulerDigest) GetVoluntarySwitches() uint64 {
	if x != nil {
		return x.VoluntarySwitches
	}
	return 0
}

func (x *SchedulerDigest) GetInvoluntarySwitches() uint64 {
	if x != nil {
		return x.InvoluntarySwitches
	}
	return 0
}

func (x *SchedulerDigest) GetLoad_1M() float64 {
	if x != nil {
		return x.Load_1M
	}
	return 0
}

type FaultDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinorFaults   uint64                 `protobuf:"varint,1,opt,name=minor_faults,json=minorFaults,proto3" json:"minor_faults,omitempty"`
	MajorFaults   uint64                 `protobuf:"varint,2,opt,name=major_faults,json=majorFaults,proto3" json:"major_faults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultDigest) Reset() {
	*x = FaultDigest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultDigest) ProtoMessage() {}

func (x *FaultDigest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultDigest.ProtoReflect.Descriptor instead.
func (*FaultDigest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *FaultDigest) GetMinorFaults() uint64 {
	if x != nil {
		return x.MinorFaults
	}
	return 0
}

func (x *FaultDigest) GetMajorFaults() uint64 {
	if x != nil {
		return x.MajorFaults
	}
	return 0
}

type SignedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameBlob     []byte                 `protobuf:"bytes,1,opt,name=frame_blob,json=frameBlob,proto3" json:"frame_blob,omitempty"` // serialized Frame message
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                  // Ed25519 signature over frame_blob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedFrame) Reset() {
	*x = SignedFrame{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedFrame) ProtoMessage() {}

func (x *SignedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedFrame.ProtoReflect.Descriptor instead.
func (*SignedFrame) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SignedFrame) GetFrameBlob() []byte {
	if x != nil {
		return x.FrameBlob
	}
	return nil
}

func (x *SignedFrame) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 over sequence||timestamp||host_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *HeartbeatRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HeartbeatResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LicenseValid        bool                   `protobuf:"varint,1,opt,name=license_valid,json=licenseValid,proto3" json:"license_valid,omitempty"`
	RotateSession       bool                   `protobuf:"varint,2,opt,name=rotate_session,json=rotateSession,proto3" json:"rotate_session,omitempty"`
	NewEncryptedPayload []byte                 `protobuf:"bytes,3,opt,name=new_encrypted_payload,json=newEncryptedPayload,proto3" json:"new_encrypted_payload,omitempty"` // optional payload rotation
	NewPayloadNonce     []byte                 `protobuf:"bytes,4,opt,name=new_payload_nonce,json=newPayloadNonce,proto3" json:"new_payload_nonce,omitempty"`
	ServerTimestampUnix int64                  `protobuf:"varint,5,opt,name=server_timestamp_unix,json=serverTimestampUnix,proto3" json:"server_timestamp_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetLicenseValid() bool {
	if x != nil {
		return x.LicenseValid
	}
	return false
}

func (x *HeartbeatResponse) GetRotateSession() bool {
	if x != nil {
		return x.RotateSession
	}
	return false
}

func (x *HeartbeatResponse) GetNewEncryptedPayload() []byte {
	if x != nil {
		return x.NewEncryptedPayload
	}
	return nil
}

func (x *HeartbeatResponse) GetNewPayloadNonce() []byte {
	if x != nil {
		return x.NewPayloadNonce
	}
	return nil
}

func (x *HeartbeatResponse) GetServerTimestampUnix() int64 {
	if x != nil {
		return x.ServerTimestampUnix
	}
	return 0
}

// ===========================================================================
// Kernel Sentinel — absence reports
// ===========================================================================
// After a restart, the agent drains its pinned eBPF ringbuf and ships any
// absence events the kernel timer recorded while it was dead. Each event is
// a moment at which the kernel detected that no pulse had been written to
// pulse_map for > PULSE_TIMEOUT_NS (120 s). Because the timer is pinned in
// bpffs, it keeps running across kill -9 / restart / upgrade cycles.
type AbsenceEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DetectedAtMs    int64                  `protobuf:"varint,1,opt,name=detected_at_ms,json=detectedAtMs,proto3" json:"detected_at_ms,omitempty"`            // wall-clock of the kernel detection
	AgentLastSeenMs int64                  `protobuf:"varint,2,opt,name=agent_last_seen_ms,json=agentLastSeenMs,proto3" json:"agent_last_seen_ms,omitempty"` // 0 when flags & never_saw_pulse
	GapSeconds      float64                `protobuf:"fixed64,3,opt,name=gap_seconds,json=gapSeconds,proto3" json:"gap_seconds,omitempty"`
	Cpu             uint32                 `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Flags           uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"` // bit 0 = never_saw_pulse
	Comm            string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	LastSeq         uint64                 `protobuf:"varint,7,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AbsenceEvent) Reset() {
	*x = AbsenceEvent{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsenceEvent) ProtoMessage() {}

func (x *AbsenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsenceEvent.ProtoReflect.Descriptor instead.
func (*AbsenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AbsenceEvent) GetDetectedAtMs() int64 {
	if x != nil {
		return x.DetectedAtMs
	}
	return 0
}

func (x *AbsenceEvent) GetAgentLastSeenMs() int64 {
	if x != nil {
		return x.AgentLastSeenMs
	}
	return 0
}

func (x *AbsenceEvent) GetGapSeconds() float64 {
	if x != nil {
		return x.GapSeconds
	}
	return 0
}

func (x *AbsenceEvent) GetCpu() uint32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *AbsenceEvent) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *AbsenceEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *AbsenceEvent) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type AbsenceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ReportBatchId string                 `protobuf:"bytes,2,opt,name=report_batch_id,json=reportBatchId,proto3" json:"report_batch_id,omitempty"` // client-generated cuid, groups one drain
	DrainedAtMs   int64                  `protobuf:"varint,3,opt,name=drained_at_ms,json=drainedAtMs,proto3" json:"drained_at_ms,omitempty"`      // wall-clock when agent drained the ringbuf
	Events        []*AbsenceEvent        `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsenceReport) Reset() {
	*x = AbsenceReport{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsenceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsenceReport) ProtoMessage() {}

func (x *AbsenceReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsenceReport.ProtoReflect.Descriptor instead.
func (*AbsenceReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AbsenceReport) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AbsenceReport) GetReportBatchId() string {
	if x != nil {
		return x.ReportBatchId
	}
	return ""
}

func (x *AbsenceReport) GetDrainedAtMs() int64 {
	if x != nil {
		return x.DrainedAtMs
	}
	return 0
}

func (x *AbsenceReport) GetEvents() []*AbsenceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// PufCellStats summarises one (core, loop-kind) cell across trials.
// Median and MAD are preferred over mean and stddev because the iteration
// rate distribution has heavy tails whenever a scheduling blip preempts
// the pinned thread.
type PufCellStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Core          uint32                 `protobuf:"varint,1,opt,name=core,proto3" json:"core,omitempty"`
	Loop          string                 `protobuf:"bytes,2,opt,name=loop,proto3" json:"loop,omitempty"`                              // "int" | "mem" | "br"
	MedianIps     float64                `protobuf:"fixed64,3,opt,name=median_ips,json=medianIps,proto3" json:"median_ips,omitempty"` // iters per second
	MadIps        float64                `protobuf:"fixed64,4,opt,name=mad_ips,json=madIps,proto3" json:"mad_ips,omitempty"`          // median absolute deviation
	Cv            float64                `protobuf:"fixed64,5,opt,name=cv,proto3" json:"cv,omitempty"`                                // coefficient of variation (Welford stddev/mean)
	MinIps        float64                `protobuf:"fixed64,6,opt,name=min_ips,json=minIps,proto3" json:"min_ips,omitempty"`
	MaxIps        float64                `protobuf:"fixed64,7,opt,name=max_ips,json=maxIps,proto3" json:"max_ips,omitempty"`
	NumSamples    uint32                 `protobuf:"varint,8,opt,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PufCellStats) Reset() {
	*x = PufCellStats{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PufCellStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PufCellStats) ProtoMessage() {}

func (x *PufCellStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PufCellStats.ProtoReflect.Descriptor instead.
func (*PufCellStats) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PufCellStats) GetCore() uint32 {
	if x != nil {
		return x.Core
	}
	return 0
}

func (x *PufCellStats) GetLoop() string {
	if x != nil {
		return x.Loop
	}
	return ""
}

func (x *PufCellStats) GetMedianIps() float64 {
	if x != nil {
		return x.MedianIps
	}
	return 0
}

func (x *PufCellStats) GetMadIps() float64 {
	if x != nil {
		return x.MadIps
	}
	return 0
}

func (x *PufCellStats) GetCv() float64 {
	if x != nil {
		return x.Cv
	}
	return 0
}

func (x *PufCellStats) GetMinIps() float64 {
	if x != nil {
		return x.MinIps
	}
	return 0
}

func (x *PufCellStats) GetMaxIps() float64 {
	if x != nil {
		return x.MaxIps
	}
	return 0
}

func (x *PufCellStats) GetNumSamples() uint32 {
	if x != nil {
		return x.NumSamples
	}
	return 0
}

type PufEnrollment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Cells         []*PufCellStats        `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	NumCores      uint32                 `protobuf:"varint,3,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	NumLoops      uint32                 `protobuf:"varint,4,opt,name=num_loops,json=numLoops,proto3" json:"num_loops,omitempty"`
	NumTrials     uint32                 `protobuf:"varint,5,opt,name=num_trials,json=numTrials,proto3" json:"num_trials,omitempty"`
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	MeasuredAtMs  int64                  `protobuf:"varint,8,opt,name=measured_at_ms,json=measuredAtMs,proto3" json:"measured_at_ms,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PufEnrollment) Reset() {
	*x = PufEnrollment{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PufEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PufEnrollment) ProtoMessage() {}

func (x *PufEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PufEnrollment.ProtoReflect.Descriptor instead.
func (*PufEnrollment) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *PufEnrollment) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *PufEnrollment) GetCells() []*PufCellStats {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *PufEnrollment) GetNumCores() uint32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *PufEnrollment) GetNumLoops() uint32 {
	if x != nil {
		return x.NumLoops
	}
	return 0
}

func (x *PufEnrollment) GetNumTrials() uint32 {
	if x != nil {
		return x.NumTrials
	}
	return 0
}

func (x *PufEnrollment) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PufEnrollment) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PufEnrollment) GetMeasuredAtMs() int64 {
	if x != nil {
		return x.MeasuredAtMs
	}
	return 0
}

func (x *PufEnrollment) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type PufAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Cells         []*PufCellStats        `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	NumCores      uint32                 `protobuf:"varint,3,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	NumLoops      uint32                 `protobuf:"varint,4,opt,name=num_loops,json=numLoops,proto3" json:"num_loops,omitempty"`
	NumTrials     uint32                 `protobuf:"varint,5,opt,name=num_trials,json=numTrials,proto3" json:"num_trials,omitempty"`
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	MeasuredAtMs  int64                  `protobuf:"varint,8,opt,name=measured_at_ms,json=measuredAtMs,proto3" json:"measured_at_ms,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PufAttestation) Reset() {
	*x = PufAttestation{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PufAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PufAttestation) ProtoMessage() {}

func (x *PufAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PufAttestation.ProtoReflect.Descriptor instead.
func (*PufAttestation) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *PufAttestation) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *PufAttestation) GetCells() []*PufCellStats {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *PufAttestation) GetNumCores() uint32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *PufAttestation) GetNumLoops() uint32 {
	if x != nil {
		return x.NumLoops
	}
	return 0
}

func (x *PufAttestation) GetNumTrials() uint32 {
	if x != nil {
		return x.NumTrials
	}
	return 0
}

func (x *PufAttestation) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PufAttestation) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PufAttestation) GetMeasuredAtMs() int64 {
	if x != nil {
		return x.MeasuredAtMs
	}
	return 0
}

func (x *PufAttestation) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type PufKeyEnrollment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HostId            string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HelperVersion     uint32                 `protobuf:"varint,2,opt,name=helper_version,json=helperVersion,proto3" json:"helper_version,omitempty"`             // matches puf.FuzzyKeyVersion
	SecretBits        uint32                 `protobuf:"varint,3,opt,name=secret_bits,json=secretBits,proto3" json:"secret_bits,omitempty"`                      // 128
	MaskBits          uint32                 `protobuf:"varint,4,opt,name=mask_bits,json=maskBits,proto3" json:"mask_bits,omitempty"`                            // 224 = (secret_bits / 4) * 7
	Indices           []uint32               `protobuf:"varint,5,rep,packed,name=indices,proto3" json:"indices,omitempty"`                                       // mask_bits values; bit positions in QuantizeV3 output
	Mask              []byte                 `protobuf:"bytes,6,opt,name=mask,proto3" json:"mask,omitempty"`                                                     // packed (mask_bits + 7) / 8 bytes
	Commitment        []byte                 `protobuf:"bytes,7,opt,name=commitment,proto3" json:"commitment,omitempty"`                                         // 32 bytes; lets the server confirm a Reproduce succeeded
	DerivedPubkey     []byte                 `protobuf:"bytes,8,opt,name=derived_pubkey,json=derivedPubkey,proto3" json:"derived_pubkey,omitempty"`              // 32-byte Ed25519 public key derived from K
	CalibrationCycles uint32                 `protobuf:"varint,9,opt,name=calibration_cycles,json=calibrationCycles,proto3" json:"calibration_cycles,omitempty"` // M used to estimate per-bit BER
	MaxBer            float64                `protobuf:"fixed64,10,opt,name=max_ber,json=maxBer,proto3" json:"max_ber,omitempty"`                                // BER ceiling at index selection
	ReliablePool      uint32                 `protobuf:"varint,11,opt,name=reliable_pool,json=reliablePool,proto3" json:"reliable_pool,omitempty"`               // total stable bits found (informational, ≥ mask_bits)
	EnrolledAtMs      int64                  `protobuf:"varint,12,opt,name=enrolled_at_ms,json=enrolledAtMs,proto3" json:"enrolled_at_ms,omitempty"`
	AgentVersion      string                 `protobuf:"bytes,13,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PufKeyEnrollment) Reset() {
	*x = PufKeyEnrollment{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PufKeyEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PufKeyEnrollment) ProtoMessage() {}

func (x *PufKeyEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PufKeyEnrollment.ProtoReflect.Descriptor instead.
func (*PufKeyEnrollment) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *PufKeyEnrollment) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *PufKeyEnrollment) GetHelperVersion() uint32 {
	if x != nil {
		return x.HelperVersion
	}
	return 0
}

func (x *PufKeyEnrollment) GetSecretBits() uint32 {
	if x != nil {
		return x.SecretBits
	}
	return 0
}

func (x *PufKeyEnrollment) GetMaskBits() uint32 {
	if x != nil {
		return x.MaskBits
	}
	return 0
}

func (x *PufKeyEnrollment) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *PufKeyEnrollment) GetMask() []byte {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *PufKeyEnrollment) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *PufKeyEnrollment) GetDerivedPubkey() []byte {
	if x != nil {
		return x.DerivedPubkey
	}
	return nil
}

func (x *PufKeyEnrollment) GetCalibrationCycles() uint32 {
	if x != nil {
		return x.CalibrationCycles
	}
	return 0
}

func (x *PufKeyEnrollment) GetMaxBer() float64 {
	if x != nil {
		return x.MaxBer
	}
	return 0
}

func (x *PufKeyEnrollment) GetReliablePool() uint32 {
	if x != nil {
		return x.ReliablePool
	}
	return 0
}

func (x *PufKeyEnrollment) GetEnrolledAtMs() int64 {
	if x != nil {
		return x.EnrolledAtMs
	}
	return 0
}

func (x *PufKeyEnrollment) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// PufKeyProof: a signed assertion that the agent could reproduce K from
// fresh silicon and therefore still controls the matching Ed25519 private
// key. The agent picks its own nonce so the server cannot prevent honest
// proofs by withholding a challenge; freshness is enforced by the
// generated_at_ms field, which the server compares against its clock.
type PufKeyProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                                         // 16 bytes random; reused across nothing
	GeneratedAtMs int64                  `protobuf:"varint,3,opt,name=generated_at_ms,json=generatedAtMs,proto3" json:"generated_at_ms,omitempty"` // unix millis, agent-claimed
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                                 // Ed25519 over host_id || nonce || generated_at_ms
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PufKeyProof) Reset() {
	*x = PufKeyProof{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PufKeyProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PufKeyProof) ProtoMessage() {}

func (x *PufKeyProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PufKeyProof.ProtoReflect.Descriptor instead.
func (*PufKeyProof) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *PufKeyProof) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *PufKeyProof) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PufKeyProof) GetGeneratedAtMs() int64 {
	if x != nil {
		return x.GeneratedAtMs
	}
	return 0
}

func (x *PufKeyProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PufKeyProof) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x12causal963.agent.v1\"\x95\x03\n" +
	"\rEnrollRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12#\n" +
	"\rx25519_public\x18\x03 \x01(\fR\fx25519Public\x12%\n" +
	"\x0ehw_fingerprint\x18\x04 \x01(\tR\rhwFingerprint\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_release\x18\a \x01(\tR\tosRelease\x12\x16\n" +
	"\x06kernel\x18\b \x01(\tR\x06kernel\x12\x1b\n" +
	"\tcpu_model\x18\t \x01(\tR\bcpuModel\x12&\n" +
	"\x0ftotal_memory_kb\x18\n" +
	" \x01(\x04R\rtotalMemoryKb\x12\x14\n" +
	"\x05nonce\x18\v \x01(\x03R\x05nonce\x12%\n" +
	"\x0etimestamp_unix\x18\f \x01(\x03R\rtimestampUnix\"\xed\x02\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12*\n" +
	"\x11server_x25519_pub\x18\x03 \x01(\fR\x0fserverX25519Pub\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\fR\x10encryptedPayload\x12#\n" +
	"\rpayload_nonce\x18\x05 \x01(\fR\fpayloadNonce\x124\n" +
	"\x16heartbeat_interval_sec\x18\x06 \x01(\rR\x14heartbeatIntervalSec\x12&\n" +
	"\x0fframe_epoch_sec\x18\a \x01(\rR\rframeEpochSec\x12(\n" +
	"\x10grace_period_sec\x18\b \x01(\rR\x0egracePeriodSec\x12\x1b\n" +
	"\tcausal_id\x18\t \x01(\tR\bcausalId\"\xac\x02\n" +
	"\vProbeConfig\x12\x1b\n" +
	"\tepoch_sec\x18\x01 \x01(\rR\bepochSec\x12%\n" +
	"\x0esyscall_probes\x18\x02 \x03(\tR\rsyscallProbes\x12)\n" +
	"\x10sample_schedstat\x18\x03 \x01(\bR\x0fsampleSchedstat\x12,\n" +
	"\x12sample_page_faults\x18\x04 \x01(\bR\x10samplePageFaults\x12$\n" +
	"\x0esample_tcp_rtt\x18\x05 \x01(\bR\fsampleTcpRtt\x12@\n" +
	"\x1chistogram_significant_digits\x18\x06 \x01(\rR\x1ahistogramSignificantDigits\x12\x18\n" +
	"\aversion\x18\a \x01(\x04R\aversion\"\xa1\x04\n" +
	"\x05Frame\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vepoch_start\x18\x03 \x01(\x03R\n" +
	"epochStart\x12\x1b\n" +
	"\tepoch_end\x18\x04 \x01(\x03R\bepochEnd\x12C\n" +
	"\fsyscall_hist\x18\x05 \x03(\v2 .causal963.agent.v1.HdrHistogramR\vsyscallHist\x129\n" +
	"\x05sched\x18\x06 \x01(\v2#.causal963.agent.v1.SchedulerDigestR\x05sched\x127\n" +
	"\x06faults\x18\a \x01(\v2\x1f.causal963.agent.v1.FaultDigestR\x06faults\x12\x1a\n" +
	"\bvertices\x18\b \x03(\x01R\bvertices\x12\x1a\n" +
	"\bgenotype\x18\t \x01(\tR\bgenotype\x12%\n" +
	"\x0ehw_fingerprint\x18\n" +
	" \x01(\tR\rhwFingerprint\x12N\n" +
	"\x0etime_consensus\x18\v \x01(\v2'.causal963.agent.v1.TimeConsensusDigestR\rtimeConsensus\x12=\n" +
	"\awitness\x18\f \x01(\v2#.causal963.agent.v1.ExternalWitnessR\awitness\"\x85\x05\n" +
	"\x13TimeConsensusDigest\x12\x12\n" +
	"\x04arch\x18\x01 \x01(\tR\x04arch\x12\x13\n" +
	"\x05hw_hz\x18\x02 \x01(\x04R\x04hwHz\x12+\n" +
	"\x12ratio_hw_vdso_mean\x18\x03 \x01(\x01R\x0fratioHwVdsoMean\x12/\n" +
	"\x14ratio_hw_vdso_stddev\x18\x04 \x01(\x01R\x11ratioHwVdsoStddev\x125\n" +
	"\x17ratio_vdso_syscall_mean\x18\x05 \x01(\x01R\x14ratioVdsoSyscallMean\x129\n" +
	"\x19ratio_vdso_syscall_stddev\x18\x06 \x01(\x01R\x16ratioVdsoSyscallStddev\x12)\n" +
	"\x11ratio_hw_hw2_mean\x18\a \x01(\x01R\x0eratioHwHw2Mean\x12-\n" +
	"\x13ratio_hw_hw2_stddev\x18\b \x01(\x01R\x10ratioHwHw2Stddev\x12#\n" +
	"\x0ehw_read_p50_ns\x18\t \x01(\x01R\vhwReadP50Ns\x12#\n" +
	"\x0ehw_read_p99_ns\x18\n" +
	" \x01(\x01R\vhwReadP99Ns\x12'\n" +
	"\x10vdso_read_p50_ns\x18\v \x01(\x01R\rvdsoReadP50Ns\x12'\n" +
	"\x10vdso_read_p99_ns\x18\f \x01(\x01R\rvdsoReadP99Ns\x12-\n" +
	"\x13syscall_read_p50_ns\x18\r \x01(\x01R\x10syscallReadP50Ns\x12-\n" +
	"\x13syscall_read_p99_ns\x18\x0e \x01(\x01R\x10syscallReadP99Ns\x12!\n" +
	"\fsample_count\x18\x0f \x01(\rR\vsampleCount\"\xd2\x01\n" +
	"\x0fExternalWitness\x12\x1d\n" +
	"\n" +
	"chain_hash\x18\x01 \x01(\tR\tchainHash\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x1e\n" +
	"\n" +
	"randomness\x18\x03 \x01(\fR\n" +
	"randomness\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12$\n" +
	"\x0ecaptured_at_ms\x18\x05 \x01(\x03R\fcapturedAtMs\x12&\n" +
	"\x0fround_time_unix\x18\x06 \x01(\x03R\rroundTimeUnix\"\x80\x02\n" +
	"\fHdrHistogram\x12\x18\n" +
	"\asyscall\x18\x01 \x01(\tR\asyscall\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x15\n" +
	"\x06p50_ns\x18\x03 \x01(\x01R\x05p50Ns\x12\x15\n" +
	"\x06p90_ns\x18\x04 \x01(\x01R\x05p90Ns\x12\x15\n" +
	"\x06p99_ns\x18\x05 \x01(\x01R\x05p99Ns\x12\x17\n" +
	"\ap999_ns\x18\x06 \x01(\x01R\x06p999Ns\x12\x1b\n" +
	"\tstddev_ns\x18\a \x01(\x01R\bstddevNs\x12\x17\n" +
	"\amean_ns\x18\b \x01(\x01R\x06meanNs\x12!\n" +
	"\fcompact_blob\x18\t \x01(\fR\vcompactBlob\"\x9d\x02\n" +
	"\x0fSchedulerDigest\x121\n" +
	"\x15runqueue_delay_p50_ns\x18\x01 \x01(\x01R\x12runqueueDelayP50Ns\x121\n" +
	"\x15runqueue_delay_p99_ns\x18\x02 \x01(\x01R\x12runqueueDelayP99Ns\x12)\n" +
	"\x10context_switches\x18\x03 \x01(\x04R\x0fcontextSwitches\x12-\n" +
	"\x12voluntary_switches\x18\x04 \x01(\x04R\x11voluntarySwitches\x121\n" +
	"\x14involuntary_switches\x18\x05 \x01(\x04R\x13involuntarySwitches\x12\x17\n" +
	"\aload_1m\x18\x06 \x01(\x01R\x06load1m\"S\n" +
	"\vFaultDigest\x12!\n" +
	"\fminor_faults\x18\x01 \x01(\x04R\vminorFaults\x12!\n" +
	"\fmajor_faults\x18\x02 \x01(\x04R\vmajorFaults\"J\n" +
	"\vSignedFrame\x12\x1d\n" +
	"\n" +
	"frame_blob\x18\x01 \x01(\fR\tframeBlob\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x8c\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xf3\x01\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\rlicense_valid\x18\x01 \x01(\bR\flicenseValid\x12%\n" +
	"\x0erotate_session\x18\x02 \x01(\bR\rrotateSession\x122\n" +
	"\x15new_encrypted_payload\x18\x03 \x01(\fR\x13newEncryptedPayload\x12*\n" +
	"\x11new_payload_nonce\x18\x04 \x01(\fR\x0fnewPayloadNonce\x122\n" +
	"\x15server_timestamp_unix\x18\x05 \x01(\x03R\x13serverTimestampUnix\"\xd9\x01\n" +
	"\fAbsenceEvent\x12$\n" +
	"\x0edetected_at_ms\x18\x01 \x01(\x03R\fdetectedAtMs\x12+\n" +
	"\x12agent_last_seen_ms\x18\x02 \x01(\x03R\x0fagentLastSeenMs\x12\x1f\n" +
	"\vgap_seconds\x18\x03 \x01(\x01R\n" +
	"gapSeconds\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\rR\x03cpu\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x19\n" +
	"\blast_seq\x18\a \x01(\x04R\alastSeq\"\xae\x01\n" +
	"\rAbsenceReport\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12&\n" +
	"\x0freport_batch_id\x18\x02 \x01(\tR\rreportBatchId\x12\"\n" +
	"\rdrained_at_ms\x18\x03 \x01(\x03R\vdrainedAtMs\x128\n" +
	"\x06events\x18\x04 \x03(\v2 .causal963.agent.v1.AbsenceEventR\x06events\"\xd1\x01\n" +
	"\fPufCellStats\x12\x12\n" +
	"\x04core\x18\x01 \x01(\rR\x04core\x12\x12\n" +
	"\x04loop\x18\x02 \x01(\tR\x04loop\x12\x1d\n" +
	"\n" +
	"median_ips\x18\x03 \x01(\x01R\tmedianIps\x12\x17\n" +
	"\amad_ips\x18\x04 \x01(\x01R\x06madIps\x12\x0e\n" +
	"\x02cv\x18\x05 \x01(\x01R\x02cv\x12\x17\n" +
	"\amin_ips\x18\x06 \x01(\x01R\x06minIps\x12\x17\n" +
	"\amax_ips\x18\a \x01(\x01R\x06maxIps\x12\x1f\n" +
	"\vnum_samples\x18\b \x01(\rR\n" +
	"numSamples\"\xb9\x02\n" +
	"\rPufEnrollment\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x126\n" +
	"\x05cells\x18\x02 \x03(\v2 .causal963.agent.v1.PufCellStatsR\x05cells\x12\x1b\n" +
	"\tnum_cores\x18\x03 \x01(\rR\bnumCores\x12\x1b\n" +
	"\tnum_loops\x18\x04 \x01(\rR\bnumLoops\x12\x1d\n" +
	"\n" +
	"num_trials\x18\x05 \x01(\rR\tnumTrials\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x01R\n" +
	"durationMs\x12$\n" +
	"\x0emeasured_at_ms\x18\b \x01(\x03R\fmeasuredAtMs\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\"\xba\x02\n" +
	"\x0ePufAttestation\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x126\n" +
	"\x05cells\x18\x02 \x03(\v2 .causal963.agent.v1.PufCellStatsR\x05cells\x12\x1b\n" +
	"\tnum_cores\x18\x03 \x01(\rR\bnumCores\x12\x1b\n" +
	"\tnum_loops\x18\x04 \x01(\rR\bnumLoops\x12\x1d\n" +
	"\n" +
	"num_trials\x18\x05 \x01(\rR\tnumTrials\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x01R\n" +
	"durationMs\x12$\n" +
	"\x0emeasured_at_ms\x18\b \x01(\x03R\fmeasuredAtMs\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\"\xbd\x03\n" +
	"\x10PufKeyEnrollment\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12%\n" +
	"\x0ehelper_version\x18\x02 \x01(\rR\rhelperVersion\x12\x1f\n" +
	"\vsecret_bits\x18\x03 \x01(\rR\n" +
	"secretBits\x12\x1b\n" +
	"\tmask_bits\x18\x04 \x01(\rR\bmaskBits\x12\x18\n" +
	"\aindices\x18\x05 \x03(\rR\aindices\x12\x12\n" +
	"\x04mask\x18\x06 \x01(\fR\x04mask\x12\x1e\n" +
	"\n" +
	"commitment\x18\a \x01(\fR\n" +
	"commitment\x12%\n" +
	"\x0ederived_pubkey\x18\b \x01(\fR\rderivedPubkey\x12-\n" +
	"\x12calibration_cycles\x18\t \x01(\rR\x11calibrationCycles\x12\x17\n" +
	"\amax_ber\x18\n" +
	" \x01(\x01R\x06maxBer\x12#\n" +
	"\rreliable_pool\x18\v \x01(\rR\freliablePool\x12$\n" +
	"\x0eenrolled_at_ms\x18\f \x01(\x03R\fenrolledAtMs\x12#\n" +
	"\ragent_version\x18\r \x01(\tR\fagentVersion\"\xa7\x01\n" +
	"\vPufKeyProof\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12&\n" +
	"\x0fgenerated_at_ms\x18\x03 \x01(\x03R\rgeneratedAtMs\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersionB*Z(github.com/963causal/agent/proto;agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_agent_proto_goTypes = []any{
	(*EnrollRequest)(nil),       // 0: causal963.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),      // 1: causal963.agent.v1.EnrollResponse
	(*ProbeConfig)(nil),         // 2: causal963.agent.v1.ProbeConfig
	(*Frame)(nil),               // 3: causal963.agent.v1.Frame
	(*TimeConsensusDigest)(nil), // 4: causal963.agent.v1.TimeConsensusDigest
	(*ExternalWitness)(nil),     // 5: causal963.agent.v1.ExternalWitness
	(*HdrHistogram)(nil),        // 6: causal963.agent.v1.HdrHistogram
	(*SchedulerDigest)(nil),     // 7: causal963.agent.v1.SchedulerDigest
	(*FaultDigest)(nil),         // 8: causal963.agent.v1.FaultDigest
	(*SignedFrame)(nil),         // 9: causal963.agent.v1.SignedFrame
	(*HeartbeatRequest)(nil),    // 10: causal963.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 11: causal963.agent.v1.HeartbeatResponse
	(*AbsenceEvent)(nil),        // 12: causal963.agent.v1.AbsenceEvent
	(*AbsenceReport)(nil),       // 13: causal963.agent.v1.AbsenceReport
	(*PufCellStats)(nil),        // 14: causal963.agent.v1.PufCellStats
	(*PufEnrollment)(nil),       // 15: causal963.agent.v1.PufEnrollment
	(*PufAttestation)(nil),      // 16: causal963.agent.v1.PufAttestation
	(*PufKeyEnrollment)(nil),    // 17: causal963.agent.v1.PufKeyEnrollment
	(*PufKeyProof)(nil),         // 18: causal963.agent.v1.PufKeyProof
}
var file_proto_agent_proto_depIdxs = []int32{
	6,  // 0: causal963.agent.v1.Frame.syscall_hist:type_name -> causal963.agent.v1.HdrHistogram
	7,  // 1: causal963.agent.v1.Frame.sched:type_name -> causal963.agent.v1.SchedulerDigest
	8,  // 2: causal963.agent.v1.Frame.faults:type_name -> causal963.agent.v1.FaultDigest
	4,  // 3: causal963.agent.v1.Frame.time_consensus:type_name -> causal963.agent.v1.TimeConsensusDigest
	5,  // 4: causal963.agent.v1.Frame.witness:type_name -> causal963.agent.v1.ExternalWitness
	12, // 5: causal963.agent.v1.AbsenceReport.events:type_name -> causal963.agent.v1.AbsenceEvent
	14, // 6: causal963.agent.v1.PufEnrollment.cells:type_name -> causal963.agent.v1.PufCellStats
	14, // 7: causal963.agent.v1.PufAttestation.cells:type_name -> causal963.agent.v1.PufCellStats
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
