// Package sentinel wraps the pinned Kernel Sentinel eBPF program.
// The BPF object + Go bindings are generated by bpf2go from
// bpf/sentinel.c. Regenerate with `go generate ./internal/sentinel/`.

package sentinel

//go:generate bpf2go -cc clang -target bpfel -cflags "-O2 -g -Wall -Werror -D__TARGET_ARCH_arm64" -type pulse_key -type pulse_value -type absence_event Sentinel bpf/sentinel.c -- -I./bpf -I/usr/include/aarch64-linux-gnu
