// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package sentinel

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SentinelAbsenceEvent struct {
	_               structs.HostLayout
	NowNs           uint64
	LastPulseNs     uint64
	LastWallclockNs uint64
	LastSeq         uint64
	Cpu             uint32
	Flags           uint32
	Comm            [16]uint8
}

type SentinelPulseKey struct {
	_      structs.HostLayout
	HostId uint32
}

type SentinelPulseValue struct {
	_           structs.HostLayout
	TimestampNs uint64
	WallclockNs uint64
	Seq         uint64
}

type SentinelTimerElem struct {
	_ structs.HostLayout
	T struct {
		_      structs.HostLayout
		Opaque [2]uint64
	}
}

// LoadSentinel returns the embedded CollectionSpec for Sentinel.
func LoadSentinel() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SentinelBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sentinel: %w", err)
	}

	return spec, err
}

// LoadSentinelObjects loads Sentinel and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SentinelObjects
//	*SentinelPrograms
//	*SentinelMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSentinelObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSentinel()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SentinelSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SentinelSpecs struct {
	SentinelProgramSpecs
	SentinelMapSpecs
	SentinelVariableSpecs
}

// SentinelProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SentinelProgramSpecs struct {
	StartTimer *ebpf.ProgramSpec `ebpf:"start_timer"`
}

// SentinelMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SentinelMapSpecs struct {
	AbsenceRingbuf *ebpf.MapSpec `ebpf:"absence_ringbuf"`
	PulseMap       *ebpf.MapSpec `ebpf:"pulse_map"`
	TimerMap       *ebpf.MapSpec `ebpf:"timer_map"`
}

// SentinelVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SentinelVariableSpecs struct {
}

// SentinelObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type SentinelObjects struct {
	SentinelPrograms
	SentinelMaps
	SentinelVariables
}

func (o *SentinelObjects) Close() error {
	return _SentinelClose(
		&o.SentinelPrograms,
		&o.SentinelMaps,
	)
}

// SentinelMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type SentinelMaps struct {
	AbsenceRingbuf *ebpf.Map `ebpf:"absence_ringbuf"`
	PulseMap       *ebpf.Map `ebpf:"pulse_map"`
	TimerMap       *ebpf.Map `ebpf:"timer_map"`
}

func (m *SentinelMaps) Close() error {
	return _SentinelClose(
		m.AbsenceRingbuf,
		m.PulseMap,
		m.TimerMap,
	)
}

// SentinelVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type SentinelVariables struct {
}

// SentinelPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type SentinelPrograms struct {
	StartTimer *ebpf.Program `ebpf:"start_timer"`
}

func (p *SentinelPrograms) Close() error {
	return _SentinelClose(
		p.StartTimer,
	)
}

func _SentinelClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sentinel_bpfel.o
var _SentinelBytes []byte
